/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package question3;

import java.awt.event.KeyEvent;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.net.ServerSocket;
import java.net.Socket;

/**
 *
 * @author Gogohaya
 */
public class ex3_client extends javax.swing.JFrame {

    /**
     * Creates new form ex3_client
     */
    
    
    static Socket s;
    static DataInputStream din;
    static DataOutputStream dout;
    
    
    public ex3_client() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        msg_text1 = new javax.swing.JTextField();
        msg_text2 = new javax.swing.JTextField();
        msg_text3 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        msg_area = new javax.swing.JTextArea();
        msg_send = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("client");

        msg_text1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msg_text1ActionPerformed(evt);
            }
        });
        msg_text1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                msg_text1KeyPressed(evt);
            }
        });

        msg_text2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                msg_text2KeyPressed(evt);
            }
        });

        msg_text3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msg_text3ActionPerformed(evt);
            }
        });
        msg_text3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                msg_text3KeyPressed(evt);
            }
        });

        msg_area.setEditable(false);
        msg_area.setColumns(20);
        msg_area.setRows(5);
        jScrollPane1.setViewportView(msg_area);

        msg_send.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        msg_send.setText("Submit");
        msg_send.setActionCommand("Submit");
        msg_send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msg_sendActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Annual Interest Rate");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Loan Amount");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Number Of Years");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(msg_text2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(msg_text3, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(msg_text1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(msg_send, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(msg_text1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(msg_text2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(msg_text3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(msg_send, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void msg_text1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msg_text1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_msg_text1ActionPerformed

    private void msg_text3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msg_text3ActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_msg_text3ActionPerformed

    private void msg_text3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_msg_text3KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            try{
            String msgout = "";
                if(msg_text1.getText().trim()=="" || msg_text2.getText().trim()=="" || msg_text3.getText().trim()==""){
                    msgout = "exit";
                    dout.writeUTF(msgout);
                }else{
            
            msgout = msg_text1.getText().trim()+" "
                    + msg_text2.getText().trim()+" "
                    + msg_text3.getText().trim();
            
            dout.writeUTF(msgout);
            msg_text1.setText("");
            msg_text2.setText("");
            msg_text3.setText("");
                }
        }catch(Exception e){
            
        }
        }
    }//GEN-LAST:event_msg_text3KeyPressed

    private void msg_text2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_msg_text2KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            try{
            String msgout = "";
                if(msg_text1.getText().trim()=="" || msg_text2.getText().trim()=="" || msg_text3.getText().trim()==""){
                    msgout = "exit";
                    dout.writeUTF(msgout);
                }else{
            
            msgout = msg_text1.getText().trim()+" "
                    + msg_text2.getText().trim()+" "
                    + msg_text3.getText().trim();
            
            dout.writeUTF(msgout);
            msg_text1.setText("");
            msg_text2.setText("");
            msg_text3.setText("");
                }
        }catch(Exception e){
            
        }
        }
    }//GEN-LAST:event_msg_text2KeyPressed

    private void msg_text1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_msg_text1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            try{
            String msgout = "";
                if(msg_text1.getText().trim()=="" || msg_text2.getText().trim()=="" || msg_text3.getText().trim()==""){
                    msgout = "exit";
                    dout.writeUTF(msgout);
                }else{
            
            msgout = msg_text1.getText().trim()+" "
                    + msg_text2.getText().trim()+" "
                    + msg_text3.getText().trim();
            
            dout.writeUTF(msgout);
            msg_text1.setText("");
            msg_text2.setText("");
            msg_text3.setText("");
                }
        }catch(Exception e){
            
        }
        }
    }//GEN-LAST:event_msg_text1KeyPressed

    private void msg_sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msg_sendActionPerformed
        // TODO add your handling code here:
        
            try{
            String msgout = "";
                if(msg_text1.getText().trim()=="" || msg_text2.getText().trim()=="" || msg_text3.getText().trim()==""){
                    msgout = "exit";
                    dout.writeUTF(msgout);
                }else{
            
            msgout = msg_text1.getText().trim()+" "
                    + msg_text2.getText().trim()+" "
                    + msg_text3.getText().trim();
            
            dout.writeUTF(msgout);
            msg_text1.setText("");
            msg_text2.setText("");
            msg_text3.setText("");
                }
        }catch(Exception e){
            
        }
        
    }//GEN-LAST:event_msg_sendActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ex3_client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ex3_client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ex3_client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ex3_client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ex3_client().setVisible(true);
            }
        });
        
        try{
            s = new Socket("localhost",1201);
            
            din = new DataInputStream(s.getInputStream());
            dout  = new DataOutputStream(s.getOutputStream());
             
            String msgin = "";
            
            while(!msgin.equals("0")){
                msgin = din.readUTF();
                String[] splited = msgin.split(" ");
		float monthly = Float.parseFloat(splited[0]);
		float totaly = Float.parseFloat(splited[1]);
                msg_area.setText(msg_area.getText().trim()+"\n Monthly Payment: "+monthly);
                msg_area.setText(msg_area.getText().trim()+"\n Total Payment:\t"+totaly);
                
            }
            msg_area.setText("Client Turn OFF");
        }catch(Exception e){
            
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTextArea msg_area;
    private javax.swing.JButton msg_send;
    private javax.swing.JTextField msg_text1;
    private javax.swing.JTextField msg_text2;
    private javax.swing.JTextField msg_text3;
    // End of variables declaration//GEN-END:variables
}
